name = "day06"
uuid = "72428e34-86bd-4065-a9de-9f06f798efe7"
authors = ["László Vaskó <1771332+vlaci@users.noreply.github.com>"]
version = "0.1.0"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
